# Generated by Django 6.0.4 on 2026-05-07 23:16

from django.db import migrations


_FORWARD_SQL = """
ALTER TABLE social_post
    ADD COLUMN content_fts LONGTEXT GENERATED ALWAYS AS (content) STORED;
ALTER TABLE social_post
    ADD FULLTEXT INDEX ft_post_content_fts (content_fts);

ALTER TABLE social_postcomment
    ADD COLUMN content_fts LONGTEXT GENERATED ALWAYS AS (content) STORED;
ALTER TABLE social_postcomment
    ADD FULLTEXT INDEX ft_postcomment_content_fts (content_fts);
"""

_REVERSE_SQL = """
ALTER TABLE social_post DROP INDEX ft_post_content_fts;
ALTER TABLE social_post DROP COLUMN content_fts;

ALTER TABLE social_postcomment DROP INDEX ft_postcomment_content_fts;
ALTER TABLE social_postcomment DROP COLUMN content_fts;
"""


def _apply_fulltext_if_mysql(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return  # SQLite / PostgreSQL — nothing to do
    try:
        schema_editor.execute(_FORWARD_SQL)
    except Exception:
        pass  # 权限不足或测试环境跳过


def _revert_fulltext_if_mysql(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    try:
        schema_editor.execute(_REVERSE_SQL)
    except Exception:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_alter_useraction_action_type_favoritepost"),
    ]

    operations = [
        migrations.RunPython(
            code=_apply_fulltext_if_mysql,
            reverse_code=_revert_fulltext_if_mysql,
        ),
    ]
