# Generated by Django 6.0.4 on 2026-05-07 23:16

from django.db import migrations


_FORWARD_SQL = """
ALTER TABLE social_post
    ADD COLUMN content_fts LONGTEXT GENERATED ALWAYS AS (content) STORED;
ALTER TABLE social_post
    ADD FULLTEXT INDEX ft_post_content_fts (content_fts);

ALTER TABLE social_postcomment
    ADD COLUMN content_fts LONGTEXT GENERATED ALWAYS AS (content) STORED;
ALTER TABLE social_postcomment
    ADD FULLTEXT INDEX ft_postcomment_content_fts (content_fts);
"""

_REVERSE_SQL = """
ALTER TABLE social_post DROP INDEX ft_post_content_fts;
ALTER TABLE social_post DROP COLUMN content_fts;

ALTER TABLE social_postcomment DROP INDEX ft_postcomment_content_fts;
ALTER TABLE social_postcomment DROP COLUMN content_fts;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_alter_useraction_action_type_favoritepost"),
    ]

    operations = [
        migrations.RunSQL(
            sql=_FORWARD_SQL,
            reverse_sql=_REVERSE_SQL,
            hints={"db_engine": "mysql"},
        ),
    ]
