# Generated by Django 6.0.4 on 2026-04-13 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('province', models.CharField(max_length=80)),
                ('cover', models.URLField()),
                ('summary', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('budget_level', models.CharField(default='中等', max_length=20)),
                ('best_season', models.CharField(blank=True, max_length=50)),
                ('score', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('is_hidden_gem', models.BooleanField(default=False)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('suggested_days', models.PositiveIntegerField(default=2)),
            ],
            options={
                'ordering': ('-score', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cover', models.URLField(blank=True)),
                ('address', models.CharField(max_length=200)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('highlights', models.CharField(blank=True, max_length=200)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='travel.destination')),
            ],
            options={
                'ordering': ('price_per_night', '-rating'),
            },
        ),
    ]
