# Generated by Django 6.0.4 on 2026-05-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_favoritedestination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tags',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
